### ISSUE TITLE
Unable to download  **cordova-plugin-xapkreader** Plugin

### ISSUE THREAD

**Issue by vijaytechlearning** [agamemnus/cordova-plugin-xapkreader#137]
Unable to download  **cordova-plugin-xapkreader** Plugin

![image](https://user-images.githubusercontent.com/34596450/57779914-be8e7780-7744-11e9-999a-0dc3c40d65a1.png)

How to download  **cordova-plugin-xapkreader** Plugin?

**Comment by agamemnus** [comment]
Undefined?

>

**Comment by vijaytechlearning** [comment]
Please tell me how to download **cordova-plugin-xapkreader** Plugin?

**Comment by agamemnus** [comment]
Look at your error messages, You will find part of the answer there.

Also, it should be:
`cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0 --variable XAPK_EXPANSION_AUTHORITY="expansion_authority" --variable XAPK_PUBLIC_KEY="YOUR_GOOGLE_PLAY_LICENSE_KEY"`

**Comment by vijaytechlearning** [comment]
Thanks,

I have added **cordova-plugin-xapkreader** plugin.

But there are one another error as
**ERROR: Could not get unknown property 'cdvCompileSdkVersion' for object of type com.android.build.gradle.LibraryExtension.**

Please help me

**Comment by agamemnus** [comment]
I thought this was fixed. Not sure. Search the issues for the word
*cdvCompileSdkVersion.*

>

**Comment by FaakhirIqbal** [comment]
First I have tried with 7.1.0 as I am using API28 in android and It is showing error while installing plugin 

cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-7.1.0 --variable XAPK_EXPANSION_AUTHORITY="expansion_authority" --variable XAPK_PUBLIC_KEY="****NBgk**************************"


```
Error: Failed to fetch plugin https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-7.1.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! git rev-list -n1 cordova-7.1.0: fatal: ambiguous argument 'cordova-7.1.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 cordova-7.1.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 cordova-7.1.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 cordova-7.1.0:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-7.1.0" "--production" "--save"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true rev-list -n1 cordova-7.1.0
npm ERR! fatal: ambiguous argument 'cordova-7.1.0': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\SVN\APK_TESTING_APP\ABC\npm-debug.log

```

and when I tried with Cordova-6.5.0 it shows error like this

```
Plugin "com.flyingsoftgames.xapkreader" already installed on android.
Installing "com.flyingsoftgames.xapkreader" for GithubBrowserwithArchitectureComponents
Unable to load PlatformApi from platform. Error: Cannot find module 'D:\SVN\APK_TESTING_APP\ABC\platforms\GithubBrowserwithArchitectureComponents\cordova\Api.js'
Failed to install 'com.flyingsoftgames.xapkreader': Error: Uncaught, unspecified "error" event. (The platform "GithubBrowserwithArchitectureComponents" does not appear to be a valid cordova platform. It is missing API.js. GithubBrowserwithArchitectureComponents not supported.)
    at EventEmitter.emit (events.js:163:17)
    at EventEmitter.module.exports.emit (C:\Users\f.iqbal\myData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\events.js:71:17)
    at Object.getPlatformApiFunction (C:\Users\f.iqbal\myData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\util.js:500:20)
    at Object.getPlatformApi (C:\Users\f.iqbal\myData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:55:25)
    at handleInstall (C:\Users\f.iqbal\myData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:593:29)
    at C:\Users\f.iqbal\myData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled 
Error: Uncaught, unspecified "error" event. (The platform "GithubBrowserwithArchitectureComponents" does not appear to be a valid cordova platform. It is missing API.js. GithubBrowserwithArchitectureComponents not supported.)


```
