### ISSUE TITLE
Crash when trying to DL the expansion file on a beta release

### ISSUE THREAD

**Issue by unskaa** [agamemnus/cordova-plugin-xapkreader#33]
I started the app and got the message "Downloading assets..." after which the app crashed immeadiately.

This is the error message from google play's crash page:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sound.moodil/com.flyingsoftgames.xapkreader.XAPKDownloaderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
	at com.flyingsoftgames.xapkreader.XAPKDownloaderActivity.onCreate(XAPKDownloaderActivity.java:75)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
	... 10 more

**Comment by agamemnus** [comment]
Are you using 5.3.1? A beta version should not initiate the downloader. If you are using 5, it is more complicated to use (check the giant issue megathread), so I suggest 5.3.1...
