### ISSUE TITLE
XAPK_PUBLIC_KEY

### ISSUE THREAD

**Issue by webplease** [agamemnus/cordova-plugin-xapkreader#56]
When install plugin I got this: (created platform with cordova platform add android@5.2.2)

Failed to install 'com.flyingsoftgames.xapkreader':Error: Variable(s) missing: XAPK_PUBLIC_KEY
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:362:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
Error: Variable(s) missing: XAPK_PUBLIC_KEY

**Comment by Slim2k** [comment]
I am also getting this issue.

Not sure if its due to xapkreader.xml not being created in  /platform/android/res/values.
