### ISSUE TITLE
Can't install Cordova 5.3.1

### ISSUE THREAD

**Issue by BobAchgill** [agamemnus/cordova-plugin-xapkreader#66]
Looks like it is a problem to install Cordova 5.3.1 .   Can't even get Hello World to create.  I uninstalled Cordova 6.x hoping to get Xapkreader working with the agamemnus/cordova-plugin-xapkreader for Cordova 5.3.1... but can't install the plugin if I cant even install Cordova 5.3.1!

Any recommendations?  I need to play video from the expansion file.

Thanks!
Bob.

**Comment by agamemnus** [comment]
I'm not sure what is happening.

You can't install Cordova 5.3.1? But that has nothing to do with the plugin... 

Go back to 6 and try agamemnus:cordova-5.3.1-auto.

**Comment by BobAchgill** [comment]
I did these steps but I don't see 

```
cordova create et-ethiopia-eth-amh-fra
cordova platform add android@latest
cordova plugin add cordova-plugin-whitelist
cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader#cordova-5.3.1-auto
```

This is the command line window...

```
F:\CORDOVA_WORKING\et-ethiopia-eth-amh-fra>cordova platform add android@latest
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.1.2
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the pro
ject
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android gr
eater than 4.0. If you have a previous platform version, you do *not* need this
plugin since the whitelist will be built in.


F:\CORDOVA_WORKING\et-ethiopia-eth-amh-fra>cordova plugin add cordova-plugin-whi
telist
Plugin "cordova-plugin-whitelist" already installed on android.

F:\CORDOVA_WORKING\et-ethiopia-eth-amh-fra>cordova plugin add https://github.com
/agamemnus/cordova-plugin-xapkreader#cordova-5.3.1-auto
Fetching plugin "https://github.com/agamemnus/cordova-plugin-xapkreader" via git
 clone
Repository "https://github.com/agamemnus/cordova-plugin-xapkreader" checked out
to git ref "cordova-5.3.1-auto".
Installing "com.flyingsoftgames.xapkreader" for android
Failed to install 'com.flyingsoftgames.xapkreader':Error: Variable(s) missing: X
APK_PUBLIC_KEY
    at C:\Users\Ownerc\AppData\Roaming\npm\node_modules\cordova\node_modules\cor
dova-lib\src\plugman\install.js:362:23
    at _fulfilled (C:\Users\Ownerc\AppData\Roaming\npm\node_modules\cordova\node
_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Ownerc\AppData\Roaming\npm\node_modul
es\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Ownerc\AppData\Roaming\npm\node
_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Ownerc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q
.js:557:44
    at flush (C:\Users\Ownerc\AppData\Roaming\npm\node_modules\cordova\node_modu
les\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Variable(s) missing: XAPK_PUBLIC_KEY

F:\CORDOVA_WORKING\et-ethiopia-eth-amh-fra>
```

Observations....

In your readme it says...

> Completing Installation:
> 
> 2) (INFO) Make sure that /platforms/android/ant-build/ and /platforms/android/ant-gen/ are deleted so that the plugin generates the necessary files when you build your APK.
> 
> 4c) In android.json, look for and modify com.test.expansion and YOUR_GOOGLE_PLAY_LICENSE_KEY in this text:
> 

```
  "res/values/xapkreader.xml": {
                "parents": {
                    "/*": [
                        {
                            "xml": "<string name=\"xapk_expansion_authority\">com.test.expansion</string>",
                            "count": 1
                        },
                        {
                            "xml": "<string name=\"xapk_google_play_public_key\">YOUR_GOOGLE_PLAY_LICENSE_KEY</string>",
                            "count": 1
                        }

```

Instead my android.json looks like this...

```
{
    
"prepare_queue": {

        "installed": [],

        "uninstalled": []

    },

    "config_munge": {

        "files": {}
 
   },
   
 "installed_plugins": {
  
      "cordova-plugin-whitelist": {
 
           "PACKAGE_NAME": "io.cordova.hellocordova"
 
       }
 
   },
    
"dependent_plugins": {}

}

```

1)  I don't see an `/platforms/android/ant-build/` and `/platforms/android/ant-gen/` to delete.

2) I don't see a place in the android.json, to put in the `com.test.expansion` and `YOUR_GOOGLE_PLAY_LICENSE_KEY`

**Comment by agamemnus** [comment]
1.


Looks like the readme was not fully updated. Check your error messages. You
need to put in XAPK_PUBLIC_KEY as a parameter when you install. I thought
it was optional...

**Comment by BobAchgill** [comment]
Put it in where?

**Comment by agamemnus** [comment]
Just in the command line when you do the install. " --variable XAPK_PUBLIC_KEY = ... " .... not sure if that is the issue, but that is the error message I see...

**Comment by BobAchgill** [comment]
Am I doing this correct?

```
F:\CORDOVA_WORKING\et-ethiopia-eth-amh-fra>cordova plugin add https://github.com
/agamemnus/cordova-plugin-xapkreader#cordova-5.3.1-auto --variable XAPK_PUBLIC_K
EY = org.hishandsreader.ethiopia_eth_amh_fra.expansion
Error: invalid variable format: XAPK_PUBLIC_KEY
```

**Comment by agamemnus** [comment]
Well, that is not the key... And you should use quotes. But in any case, something else is wrong...

**Comment by agamemnus** [comment]
Once you use quotes, and use the key (not your expansion authority), that should work.

I updated the text a little bit as well as the settings. So, here is what I did.

First, I updated Android SDK tools and SDK Platform-tools to latest -- Tools, 25.2.5; Platform-tools, 25.0.3.

Then, I updated Cordova to latest -- 6.5.0.

Then:

```
cordova create test
cd test
cordova platform add android@latest
cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0 --variable XAPK_EXPANSION_AUTHORITY="your_expansion_authority" --variable XAPK_PUBLIC_KEY="your_google_play_license_key"
```
